using Enter.UI.Abstractions.Components.Icon;

namespace Enter.UI.Providers;

public class FontAwesomeIconProvider : IEntIconProvider
{
    
    private static Dictionary<EntIconName, string> names = new()
    {
        { EntIconName.Add, "fa-plus" },
        { EntIconName.Adjust, "fa-adjust" },
        { EntIconName.AlignCenter, "fa-align-center" },
        { EntIconName.AlignJustify, "fa-align-justify" },
        { EntIconName.AlignLeft, "fa-align-left" },
        { EntIconName.AlignRight, "fa-align-right" },
        { EntIconName.AngleDown, "fa-angle-down" },
        { EntIconName.AngleLeft, "fa-angle-left" },
        { EntIconName.AngleRight, "fa-angle-right" },
        { EntIconName.AngleUp, "fa-angle-up" },
        { EntIconName.Archive, "fa-archive" },
        { EntIconName.ArrowAltCircleDown, "fa-arrow-alt-circle-down" },
        { EntIconName.ArrowDown, "fa-arrow-down" },
        { EntIconName.ArrowLeft, "fa-arrow-left" },
        { EntIconName.ArrowRight, "fa-arrow-right" },
        { EntIconName.ArrowUp, "fa-arrow-up" },
        { EntIconName.Baby, "fa-baby" },
        { EntIconName.BabyCarriage, "fa-baby-carriage" },
        { EntIconName.Backspace, "fa-backspace" },
        { EntIconName.Backward, "fa-backward" },
        { EntIconName.BalanceScale, "fa-balance-scale" },
        { EntIconName.Ban, "fa-ban" },
        { EntIconName.BandAid, "fa-band-aid" },
        { EntIconName.Bars, "fa-bars" },
        { EntIconName.BatteryFull, "fa-battery-full" },
        { EntIconName.Bell, "fa-bell" },
        { EntIconName.BellSlash, "fa-bell-slash" },
        { EntIconName.Biking, "fa-biking" },
        { EntIconName.BirthdayCake, "fa-birthday-cake" },
        { EntIconName.Bold, "fa-bold" },
        { EntIconName.Bolt, "fa-bolt" },
        { EntIconName.Book, "fa-book" },
        { EntIconName.Bookmark, "fa-bookmark" },
        { EntIconName.BookReader, "fa-book-reader" },
        { EntIconName.BorderAll, "fa-border-all" },
        { EntIconName.BorderNone, "fa-border-none" },
        { EntIconName.BorderStyle, "fa-border-style" },
        { EntIconName.Briefcase, "fa-briefcase" },
        { EntIconName.Brush, "fa-brush" },
        { EntIconName.Bug, "fa-bug" },
        { EntIconName.Building, "fa-building" },
        { EntIconName.Bus, "fa-bus" },
        { EntIconName.CalendarCheck, "fa-calendar-check" },
        { EntIconName.CalendarDay, "fa-calendar-day" },
        { EntIconName.CalendarTimes, "fa-calendar-times" },
        { EntIconName.CalendarWeek, "fa-calendar-week" },
        { EntIconName.Camera, "fa-camera" },
        { EntIconName.CameraRetro, "fa-camera-retro" },
        { EntIconName.Car, "fa-car" },
        { EntIconName.CaretSquareRight, "fa-caret-square-right" },
        { EntIconName.CartPlus, "fa-cart-plus" },
        { EntIconName.Chair, "fa-chair" },
        { EntIconName.ChartPie, "fa-chart-pie" },
        { EntIconName.Check, "fa-check" },
        { EntIconName.CheckCircle, "fa-check-circle" },
        { EntIconName.CheckDouble, "fa-check-double" },
        { EntIconName.CheckSquare, "fa-check-square" },
        { EntIconName.ChevronLeft, "fa-chevron-left" },
        { EntIconName.ChevronRight, "fa-chevron-right" },
        { EntIconName.ChevronUp, "fa-chevron-up" },
        { EntIconName.ChevronDown, "fa-chevron-down" },
        { EntIconName.Circle, "fa-circle" },
        { EntIconName.City, "fa-city" },
        { EntIconName.Clear, "fa-eraser" },
        { EntIconName.ClinicMedical, "fa-clinic-medical" },
        { EntIconName.Clock, "fa-clock" },
        { EntIconName.ClosedCaptioning, "fa-closed-captioning" },
        { EntIconName.Cloud, "fa-cloud" },
        { EntIconName.CloudDownloadAlt, "fa-cloud-download-alt" },
        { EntIconName.CloudUploadAlt, "fa-cloud-upload-alt" },
        { EntIconName.Cocktail, "fa-cocktail" },
        { EntIconName.Code, "fa-code" },
        { EntIconName.Coffee, "fa-coffee" },
        { EntIconName.Comment, "fa-comment" },
        { EntIconName.CommentAlt, "fa-comment-alt" },
        { EntIconName.Comments, "fa-comments" },
        { EntIconName.CompactDisc, "fa-compact-disc" },
        { EntIconName.Compass, "fa-compass" },
        { EntIconName.Compress, "fa-compress" },
        { EntIconName.Copyright, "fa-copyright" },
        { EntIconName.CreditCard, "fa-credit-card" },
        { EntIconName.Crop, "fa-crop" },
        { EntIconName.Dashboard, "fa-columns" },
        { EntIconName.Delete, "fa-trash" },
        { EntIconName.Desktop, "fa-desktop" },
        { EntIconName.Dice, "fa-dice" },
        { EntIconName.Directions, "fa-directions" },
        { EntIconName.Dog, "fa-dog" },
        { EntIconName.DollarSign, "fa-dollar-sign" },
        { EntIconName.DotCircle, "fa-dot-circle" },
        { EntIconName.Download, "fa-download" },
        { EntIconName.Dumbbell, "fa-dumbbell" },
        { EntIconName.Edit, "fa-edit" },
        { EntIconName.Eject, "fa-eject" },
        { EntIconName.Ethernet, "fa-ethernet" },
        { EntIconName.EuroSign, "fa-euro-sign" },
        { EntIconName.Exclamation, "fa-exclamation" },
        { EntIconName.ExclamationCircle, "fa-exclamation-circle" },
        { EntIconName.ExclamationTriangle, "fa-exclamation-triangle" },
        { EntIconName.Expand, "fa-expand" },
        { EntIconName.ExpandArrowsAlt, "fa-expand-arrows-alt" },
        { EntIconName.ExpandLess, "fa-chevron-up" },
        { EntIconName.ExpandMore, "fa-chevron-down" },
        { EntIconName.ExternalLinkSquareAlt, "fa-external-link-square-alt" },
        { EntIconName.Eye, "fa-eye" },
        { EntIconName.EyeSlash, "fa-eye-slash" },
        { EntIconName.FastForward, "fa-fast-forward" },
        { EntIconName.FileAlt, "fa-file-alt" },
        { EntIconName.FileDownload, "fa-file-download" },
        { EntIconName.FilePdf, "fa-file-pdf" },
        { EntIconName.FileUpload, "fa-file-upload" },
        { EntIconName.Film, "fa-film" },
        { EntIconName.Filter, "fa-filter" },
        { EntIconName.Fingerprint, "fa-fingerprint" },
        { EntIconName.Fire, "fa-fire" },
        { EntIconName.Flag, "fa-flag" },
        { EntIconName.Flask, "fa-flask" },
        { EntIconName.Folder, "fa-folder" },
        { EntIconName.FolderOpen, "fa-folder-open" },
        { EntIconName.FolderPlus, "fa-folder-plus" },
        { EntIconName.Forward, "fa-forward" },
        { EntIconName.Frown, "fa-frown" },
        { EntIconName.FrownOpen, "fa-frown-open" },
        { EntIconName.Gamepad, "fa-gamepad" },
        { EntIconName.GasPump, "fa-gas-pump" },
        { EntIconName.Gavel, "fa-gavel" },
        { EntIconName.Gift, "fa-gift" },
        { EntIconName.Grin, "fa-grin" },
        { EntIconName.GripLines, "fa-grip-lines" },
        { EntIconName.GripVertical, "fa-grip-vertical" },
        { EntIconName.HandPaper, "fa-hand-paper" },
        { EntIconName.HandsHelping, "fa-hands-helping" },
        { EntIconName.Headphones, "fa-headphones" },
        { EntIconName.Headset, "fa-headset" },
        { EntIconName.Heart, "fa-heart" },
        { EntIconName.Highlighter, "fa-highlighter" },
        { EntIconName.History, "fa-history" },
        { EntIconName.Home, "fa-home" },
        { EntIconName.Hospital, "fa-hospital" },
        { EntIconName.Hotel, "fa-hotel" },
        { EntIconName.HotTub, "fa-hot-tub" },
        { EntIconName.Hourglass, "fa-hourglass" },
        { EntIconName.IdCard, "fa-id-card" },
        { EntIconName.Image, "fa-image" },
        { EntIconName.Images, "fa-images" },
        { EntIconName.Inbox, "fa-inbox" },
        { EntIconName.Indent, "fa-indent" },
        { EntIconName.Infinity, "fa-infinity" },
        { EntIconName.Info, "fa-info" },
        { EntIconName.InfoCircle, "fa-info-circle" },
        { EntIconName.Italic, "fa-italic" },
        { EntIconName.Key, "fa-key" },
        { EntIconName.Keyboard, "fa-keyboard" },
        { EntIconName.Language, "fa-language" },
        { EntIconName.Laptop, "fa-laptop" },
        { EntIconName.LaptopCode, "fa-laptop-code" },
        { EntIconName.Laugh, "fa-laugh" },
        { EntIconName.LayerGroup, "fa-layer-group" },
        { EntIconName.Lightbulb, "fa-lightbulb" },
        { EntIconName.Link, "fa-link" },
        { EntIconName.List, "fa-list" },
        { EntIconName.ListOl, "fa-list-ol" },
        { EntIconName.ListUl, "fa-list-ul" },
        { EntIconName.LocationArrow, "fa-location-arrow" },
        { EntIconName.Lock, "fa-lock" },
        { EntIconName.LockOpen, "fa-lock-open" },
        { EntIconName.Mail, "fa-envelope" },
        { EntIconName.Map, "fa-map" },
        { EntIconName.Moon, "fa-moon" },
        { EntIconName.MapMarker, "fa-map-marker" },
        { EntIconName.MapMarkerAlt, "fa-map-marker-alt" },
        { EntIconName.Memory, "fa-memory" },
        { EntIconName.Microphone, "fa-microphone" },
        { EntIconName.MicrophoneSlash, "fa-microphone-slash" },
        { EntIconName.MinusCircle, "fa-minus-circle" },
        { EntIconName.MinusSquare, "fa-minus-square" },
        { EntIconName.MoneyBillAlt, "fa-money-bill-alt" },
        { EntIconName.MoreHorizontal, "fa-ellipsis-h" },
        { EntIconName.MoreVertical, "fa-ellipsis-v" },
        { EntIconName.Motorcycle, "fa-motorcycle" },
        { EntIconName.Mouse, "fa-mouse" },
        { EntIconName.Music, "fa-music" },
        { EntIconName.PaintBrush, "fa-paint-brush" },
        { EntIconName.PaintRoller, "fa-paint-roller" },
        { EntIconName.Palette, "fa-palette" },
        { EntIconName.Paperclip, "fa-paperclip" },
        { EntIconName.PaperPlane, "fa-paper-plane" },
        { EntIconName.Parking, "fa-parking" },
        { EntIconName.Pause, "fa-pause" },
        { EntIconName.PauseCircle, "fa-pause-circle" },
        { EntIconName.Pen, "fa-pen" },
        { EntIconName.Phone, "fa-phone" },
        { EntIconName.PhoneAlt, "fa-phone-alt" },
        { EntIconName.PizzaSlice, "fa-pizza-slice" },
        { EntIconName.Plane, "fa-plane" },
        { EntIconName.PlaneArrival, "fa-plane-arrival" },
        { EntIconName.PlaneDeparture, "fa-plane-departure" },
        { EntIconName.Play, "fa-play" },
        { EntIconName.PlayCircle, "fa-play-circle" },
        { EntIconName.Plug, "fa-plug" },
        { EntIconName.PlusCircle, "fa-plus-circle" },
        { EntIconName.PlusSquare, "fa-plus-square" },
        { EntIconName.Poll, "fa-poll" },
        { EntIconName.Portrait, "fa-portrait" },
        { EntIconName.Print, "fa-print" },
        { EntIconName.PuzzlePiece, "fa-puzzle-piece" },
        { EntIconName.QuestionCircle, "fa-question-circle" },
        { EntIconName.QuoteRight, "fa-quote-right" },
        { EntIconName.Random, "fa-random" },
        { EntIconName.Receipt, "fa-receipt" },
        { EntIconName.Redo, "fa-redo" },
        { EntIconName.Remove, "fa-minus" },
        { EntIconName.RemoveFormat, "fa-remove-format" },
        { EntIconName.Reply, "fa-reply" },
        { EntIconName.ReplyAll, "fa-reply-all" },
        { EntIconName.Restroom, "fa-restroom" },
        { EntIconName.Rss, "fa-rss" },
        { EntIconName.RulerHorizontal, "fa-ruler-horizontal" },
        { EntIconName.Running, "fa-running" },
        { EntIconName.Satellite, "fa-satellite" },
        { EntIconName.Save, "fa-save" },
        { EntIconName.School, "fa-school" },
        { EntIconName.SdCard, "fa-sd-card" },
        { EntIconName.Search, "fa-search" },
        { EntIconName.SearchMinus, "fa-search-minus" },
        { EntIconName.SearchPlus, "fa-search-plus" },
        { EntIconName.Seedling, "fa-seedling" },
        { EntIconName.Server, "fa-server" },
        { EntIconName.Shapes, "fa-shapes" },
        { EntIconName.Share, "fa-share" },
        { EntIconName.ShareAlt, "fa-share-alt" },
        { EntIconName.ShieldAlt, "fa-shield-alt" },
        { EntIconName.Ship, "fa-ship" },
        { EntIconName.ShoppingBag, "fa-shopping-bag" },
        { EntIconName.ShoppingBasket, "fa-shopping-basket" },
        { EntIconName.ShoppingCart, "fa-shopping-cart" },
        { EntIconName.ShuttleVan, "fa-shuttle-van" },
        { EntIconName.SimCard, "fa-sim-card" },
        { EntIconName.SliderHorizontal, "fa-sliders-h" },
        { EntIconName.Smartphone, "fa-mobile" },
        { EntIconName.Smile, "fa-smile" },
        { EntIconName.Smoking, "fa-smoking" },
        { EntIconName.SmokingBan, "fa-smoking-ban" },
        { EntIconName.Sms, "fa-sms" },
        { EntIconName.Snowflake, "fa-snowflake" },
        { EntIconName.Sort, "fa-sort" },
        { EntIconName.SortAlphaDown, "fa-sort-alpha-down" },
        { EntIconName.SortAmountDownAlt, "fa-sort-amount-down-alt" },
        { EntIconName.SortDown, "fa-sort-down" },
        { EntIconName.SortUp, "fa-sort-up" },
        { EntIconName.Spa, "fa-spa" },
        { EntIconName.SpellCheck, "fa-spell-check" },
        { EntIconName.Square, "fa-square" },
        { EntIconName.Star, "fa-star" },
        { EntIconName.StarHalf, "fa-star-half" },
        { EntIconName.StepBackward, "fa-step-backward" },
        { EntIconName.StepForward, "fa-step-forward" },
        { EntIconName.StickyNote, "fa-sticky-note" },
        { EntIconName.Stop, "fa-stop" },
        { EntIconName.Store, "fa-store" },
        { EntIconName.StoreAlt, "fa-store-alt" },
        { EntIconName.Stream, "fa-stream" },
        { EntIconName.StreetView, "fa-street-view" },
        { EntIconName.Strikethrough, "fa-strikethrough" },
        { EntIconName.Subscript, "fa-subscript" },
        { EntIconName.Subway, "fa-subway" },
        { EntIconName.Suitcase, "fa-suitcase" },
        { EntIconName.Sun, "fa-sun" },
        { EntIconName.Superscript, "fa-superscript" },
        { EntIconName.SwimmingPool, "fa-swimming-pool" },
        { EntIconName.Sync, "fa-sync" },
        { EntIconName.SyncAlt, "fa-sync-alt" },
        { EntIconName.Tablet, "fa-tablet" },
        { EntIconName.Tag, "fa-tag" },
        { EntIconName.Taxi, "fa-taxi" },
        { EntIconName.TextHeight, "fa-text-height" },
        { EntIconName.ThumbsDown, "fa-thumbs-down" },
        { EntIconName.ThumbsUp, "fa-thumbs-up" },
        { EntIconName.TicketAlt, "fa-ticket-alt" },
        { EntIconName.Times, "fa-times" },
        { EntIconName.TimesCircle, "fa-times-circle" },
        { EntIconName.Tint, "fa-tint" },
        { EntIconName.TintSlash, "fa-tint-slash" },
        { EntIconName.TrafficLight, "fa-traffic-light" },
        { EntIconName.Train, "fa-train" },
        { EntIconName.Tram, "fa-tram" },
        { EntIconName.Tree, "fa-tree" },
        { EntIconName.Truck, "fa-truck" },
        { EntIconName.Tv, "fa-tv" },
        { EntIconName.UmbrellaBeach, "fa-umbrella-beach" },
        { EntIconName.Underline, "fa-underline" },
        { EntIconName.Undo, "fa-undo" },
        { EntIconName.Unlock, "fa-unlock" },
        { EntIconName.User, "fa-user" },
        { EntIconName.UserCheck, "fa-user-check" },
        { EntIconName.UserCircle, "fa-user-circle" },
        { EntIconName.UserFriends, "fa-user-friends" },
        { EntIconName.UserPlus, "fa-user-plus" },
        { EntIconName.Users, "fa-users" },
        { EntIconName.UserTie, "fa-user-tie" },
        { EntIconName.Utensils, "fa-utensils" },
        { EntIconName.Video, "fa-video" },
        { EntIconName.VideoSlash, "fa-video-slash" },
        { EntIconName.Voicemail, "fa-voicemail" },
        { EntIconName.VolumeDown, "fa-volume-down" },
        { EntIconName.VolumeMute, "fa-volume-mute" },
        { EntIconName.VolumeOff, "fa-volume-off" },
        { EntIconName.VolumeUp, "fa-volume-up" },
        { EntIconName.Walking, "fa-walking" },
        { EntIconName.Wallet, "fa-wallet" },
        { EntIconName.Wheelchair, "fa-wheelchair" },
        { EntIconName.Wifi, "fa-wifi" },
        { EntIconName.WineBottle, "fa-wine-bottle" },
        { EntIconName.Wrench, "fa-wrench" },
    };
    
    private static Dictionary<EntIconNametyle, string> styles = new()
    {
        { EntIconNametyle.Solid, "fas" },
        { EntIconNametyle.Regular, "far" },
        { EntIconNametyle.Light, "fal" },
        { EntIconNametyle.DuoTone, "fad" },
    };
    
    public string GetIconName(EntIconName name)
    {
        return names[name];
    }

    public string GetIconStyle(EntIconNametyle name)
    {
        return styles[name];
    }
    
    
    public  string Icon( object name, EntIconNametyle style )
    {
        var iconStyle = GetIconStyle( style );

        if ( name is EntIconName iconEnum )
        {
            return $"{iconStyle} {GetIconName( iconEnum)}".Trim();
        }
        else if ( name is string iconName )
        {
            return $"{iconStyle} {iconName}".Trim();
        }
        return iconStyle;
    }

}